version: '3'
services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xiaomi
      POSTGRES_DB: real-time-chat
    ports:
      - 5490:5432
